### ISSUE TITLE
Traefik | Error occurred while proxying request

### ISSUE THREAD

**Issue by yehoshuasandler** [bmcgonag/quant-ux-docker#4]
When putting these services behind Traefik as a reverse proxy the following error is logged out at signup/login (and probably with any particular server call):

```
quant-ux-frontend | [HPM] Error occurred while proxying request my.domain.name/rest/login/ to http://quant-ux-backend:8080/ [EAI_AGAIN] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

There are no issues logging from any of the services other than this one

My Traefik setup in this docker-compose looks like such:

```
// out side the services
networks:
  web:
    external: true

// inside the FE service
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.quant.entrypoints=web,websecure,traefik
      - traefik.http.routers.quant.tls.certresolver=lets-encrypt
      - traefik.http.routers.quant.rule=Host(`my.domain.name`)
      - traefik.port=80 // also have done 443
```

I've used this same traefik config for all of my other services with no issue so I am a little lost for what options to explore.
